### ISSUE TITLE
another problem is here.

### ISSUE THREAD

**Issue by SaintyLiu** [jackie840129/STE-NVAN#20]
Start dataloader...
End dataloader...
Inference: 100%|██████████████████████████████████████████████████| 130/130 [00:50<00:00, 2.59it/s]
Traceback (most recent call last):
File "evaluate.py", line 86, in
cmc, map = validation(network, test_dataloader, args)
File "evaluate.py", line 58, in validation
gallery_cams, dataloader.dataset.query_idx, 10000)
File "/home/lq/code/person-ReID/STE-NVAN/util/cmc.py", line 20, in Video_Cmc
q_data = {k:v[q_idx] for k, v in data.items()}
File "/home/lq/code/person-ReID/STE-NVAN/util/cmc.py", line 20, in
q_data = {k:v[q_idx] for k, v in data.items()}
IndexError: index 8298 is out of bounds for axis 0 with size 8298
run_evaluate.sh: 12: run_evaluate.sh: --batch_size: not found

I have another problem.

**Comment by jackie840129** [comment]
You can check whether your q_idx start from 0.
